### ISSUE TITLE
Missing default value for cooldown in generated config results in crash on first launch

### ISSUE THREAD

**Issue by seasonedfish** [SilverAndro/itemflexer#1]
ItemFlexer 1.1.1, Fabric 0.10.8
Crash Report: https://paste.ee/p/VGob0

**Comment by SilverAndro** [comment]
That looks like you messed up the config file, make sure it's in a proper format

**Comment by seasonedfish** [comment]
That's strange, that was the first time I launched the mod, so I didn't have the chance to modify the config.

**Comment by seasonedfish** [comment]
Ah, I see. There's no default value for `cooldown` when the config file generates; setting it to 0 fixes this.

**Comment by SilverAndro** [comment]
Strange, that shouldn't be possible

**Comment by SilverAndro** [comment]
Yeah looking at microconfig's code that value should always be set, unless their some quirk of reflection or file writers I can't find easily

Is this consistent behavior? (Always happens when the config file is missing?)

**Comment by SilverAndro** [comment]
Fixed in latest version
