### ISSUE TITLE
Config for text values + formatting

### ISSUE THREAD

**Issue by ghost** [SilverAndro/itemflexer#3]
hello could you add text editing to the config for possible translations and changing the color of the text?

**Comment by SilverAndro** [comment]
Yes this is planned eventually

**Comment by SilverAndro** [comment]
Done in 1.2.0

**Comment by ghost** [comment]
Okay, but could you add a second sentence Empty hand message ?
and how to use color codes? simple §3 ?

**Comment by SilverAndro** [comment]
Oh sorry I forgot about the failure message
and yes thats the only way to do it

**Comment by SilverAndro** [comment]
Done in 1.2.1

**Comment by ghost** [comment]
you are super fast in support I appreciate it.. after today testing everything works great but I encountered a problem with the fact that in the config can not color player_name and item_name .. after coloring they remain in the chat white

**Comment by SilverAndro** [comment]
How did you try to color them

**Comment by ghost** [comment]
chatMessage=§8§l[§c§li§8§l] §6%player:displayname% §ezaflexil s §6%itemflexer:item%

**Comment by SilverAndro** [comment]
Seems like an issue with the API im using, cant do anything about it sorry
