### ISSUE TITLE
Feature Request: Add ability to display when there is more of one item held in hand

### ISSUE THREAD

**Issue by zachthedev** [SilverAndro/itemflexer#6]
When there is more than one of an item, allow a placeholder that says how many. So the template could be Flex: 1 x Chicken or like Flex: 37 x Diamonds

**Comment by SilverAndro** [comment]
Hm good idea, ill likely add that as an optional branch so 

`/flex`, `/flex <slot>`,  `/flex showCount`, and `/flex showCount <slot>`

**Comment by SilverAndro** [comment]
Implemented in 1.3.0

**Comment by zachthedev** [comment]
Thanks!
